# Generated by Django 3.2.6 on 2021-08-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NRI',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('details', models.CharField(default='NULL', max_length=200)),
                ('des', models.URLField()),
                ('publish', models.DateField()),
                ('image', models.URLField()),
            ],
        ),
    ]
