# Generated by Django 3.2.6 on 2021-08-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_nri_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='nri',
            name='posttime',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
